# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Denoken < Formula
  desc ""
  homepage "https://github.com/sandricoprovo/homebrew-denoken"
  version "0.1.8"

  on_macos do
    url "https://github.com/sandricoprovo/homebrew-denoken/releases/download/v0.1.8/homebrew-denoken_0.1.8_darwin_all.tar.gz"
    sha256 "c3f6bb6a5e4695bb651fe812dfe430c32eaa74a14d7004d8580734e662a158c0"

    def install
      bin.install "homebrew-denoken"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandricoprovo/homebrew-denoken/releases/download/v0.1.8/homebrew-denoken_0.1.8_linux_arm64.tar.gz"
      sha256 "109dd5657351d367d131fd0cd641035b76c10cd9dc1c5eb66a40fc2229aa4c41"

      def install
        bin.install "denoken"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandricoprovo/homebrew-denoken/releases/download/v0.1.8/homebrew-denoken_0.1.8_linux_amd64.tar.gz"
      sha256 "ce46af31241dede8367999555ba4c3747cabc455d93386d04d4fc4e54d40b0e7"

      def install
        bin.install "denoken"
      end
    end
  end
end
