# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Denoken < Formula
  desc ""
  homepage "https://github.com/sandricoprovo/denoken"
  version "0.1.9"

  on_macos do
    url "https://github.com/sandricoprovo/denoken/releases/download/v0.1.9/denoken_0.1.9_darwin_all.tar.gz"
    sha256 "52ca6e277ac73df9899be716f4b7448eebe429444c15414cd421fa14222aa90b"

    def install
      bin.install "denoken"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandricoprovo/denoken/releases/download/v0.1.9/denoken_0.1.9_linux_arm64.tar.gz"
      sha256 "a72b1715790227640362f0ceafe54c5866e03f97f065dc41ca3aad96876badfd"

      def install
        bin.install "denoken"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sandricoprovo/denoken/releases/download/v0.1.9/denoken_0.1.9_linux_amd64.tar.gz"
      sha256 "68f66825bc699285fb2370fbecf886d2e18335933fdc66f04b4c7d85d091ad1e"

      def install
        bin.install "denoken"
      end
    end
  end
end
